FROM python:3.12
WORKDIR /app

ENV PYTHONPATH="${PYTHONPATH}:/app"

COPY requirements.txt ./
COPY mental_health_docs.json ./
RUN pip install -r requirements.txt
COPY . /app/
CMD ["python","-u","chroma/chroma.py"]
